package:
  name: filterpy
  version: "0.1.3"

source:
  fn: filterpy-0.1.3.tar.gz
  url: https://pypi.python.org/packages/source/f/filterpy/filterpy-0.1.3.tar.gz
  md5: ba1e6fb84efaae3d21a73ba9fb563cab
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - filterpy = filterpy:main
    #
    # Would create an entry point called filterpy that calls filterpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python >=2.7
    - setuptools
    - numpy
    - scipy
    - matplotlib

  run:
    - python >=2.7
    - numpy
    - scipy
    - matplotlib

test:
  # Python imports
  imports:
    - filterpy
    - filterpy.common
    - filterpy.discrete_bayes
    - filterpy.examples
    - filterpy.gh
    - filterpy.hinfinity
    - filterpy.kalman
    - filterpy.leastsq
    - filterpy.memory
    - filterpy.monte_carlo
    - filterpy.stats

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/rlabbe/filterpy
  license: MIT License
  summary: 'Kalman filtering and optimal estimation library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
